# Generated by Django 5.0.6 on 2024-07-08 09:25

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='recruiterprofile',
            name='myuser',
        ),
        migrations.RemoveField(
            model_name='seekerprofile',
            name='myuser',
        ),
        migrations.RenameField(
            model_name='customuser',
            old_name='company_address',
            new_name='Father_name',
        ),
        migrations.RenameField(
            model_name='customuser',
            old_name='company_name',
            new_name='Mother_name',
        ),
        migrations.RenameField(
            model_name='customuser',
            old_name='display_name',
            new_name='city',
        ),
        migrations.RenameField(
            model_name='customuser',
            old_name='education',
            new_name='education_qualification',
        ),
        migrations.RenameField(
            model_name='customuser',
            old_name='qualifications',
            new_name='emergency_contact',
        ),
        migrations.RenameField(
            model_name='customuser',
            old_name='skills',
            new_name='phone',
        ),
        migrations.RenameField(
            model_name='jobmodel',
            old_name='number_of_openings',
            new_name='Company_location',
        ),
        migrations.RenameField(
            model_name='jobmodel',
            old_name='skills',
            new_name='Company_name',
        ),
        migrations.RenameField(
            model_name='jobmodel',
            old_name='title',
            new_name='Qualifications',
        ),
        migrations.RemoveField(
            model_name='customuser',
            name='company_description',
        ),
        migrations.RemoveField(
            model_name='customuser',
            name='resume',
        ),
        migrations.RemoveField(
            model_name='customuser',
            name='usertype',
        ),
        migrations.RemoveField(
            model_name='jobmodel',
            name='category',
        ),
        migrations.RemoveField(
            model_name='jobmodel',
            name='job_description',
        ),
        migrations.AddField(
            model_name='customuser',
            name='gender',
            field=models.CharField(choices=[('male', 'Male'), ('female', 'Female'), ('other', 'Other')], max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='customuser',
            name='picture',
            field=models.ImageField(null=True, upload_to='Picture'),
        ),
        migrations.AddField(
            model_name='customuser',
            name='role',
            field=models.CharField(choices=[('recruiter', 'Recruiter'), ('job_seeker', 'Job_Seeker')], max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='customuser',
            name='work_experience',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='jobmodel',
            name='Company_logo',
            field=models.ImageField(null=True, upload_to='Picture'),
        ),
        migrations.AddField(
            model_name='jobmodel',
            name='company_description',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='jobmodel',
            name='deadline',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='jobmodel',
            name='job_title',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='jobmodel',
            name='salary',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.CreateModel(
            name='JobApplyModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('resume', models.FileField(null=True, upload_to='resume')),
                ('experience', models.CharField(max_length=100, null=True)),
                ('apply_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('apply_to', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='myapp.jobmodel')),
            ],
        ),
        migrations.DeleteModel(
            name='applyjob',
        ),
        migrations.DeleteModel(
            name='recruiterprofile',
        ),
        migrations.DeleteModel(
            name='seekerprofile',
        ),
    ]
