# Generated by Django 5.0.6 on 2024-07-08 09:31

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0002_remove_recruiterprofile_myuser_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='customuser',
            old_name='Father_name',
            new_name='display_name',
        ),
        migrations.RenameField(
            model_name='customuser',
            old_name='role',
            new_name='usertype',
        ),
        migrations.RenameField(
            model_name='jobmodel',
            old_name='Company_logo',
            new_name='category',
        ),
        migrations.RenameField(
            model_name='jobmodel',
            old_name='Company_location',
            new_name='jobDescription',
        ),
        migrations.RenameField(
            model_name='jobmodel',
            old_name='Company_name',
            new_name='numberOfOpenings',
        ),
        migrations.RenameField(
            model_name='jobmodel',
            old_name='Qualifications',
            new_name='skill',
        ),
        migrations.RenameField(
            model_name='jobmodel',
            old_name='company_description',
            new_name='title',
        ),
        migrations.RemoveField(
            model_name='customuser',
            name='Mother_name',
        ),
        migrations.RemoveField(
            model_name='customuser',
            name='city',
        ),
        migrations.RemoveField(
            model_name='customuser',
            name='education_qualification',
        ),
        migrations.RemoveField(
            model_name='customuser',
            name='emergency_contact',
        ),
        migrations.RemoveField(
            model_name='customuser',
            name='gender',
        ),
        migrations.RemoveField(
            model_name='customuser',
            name='phone',
        ),
        migrations.RemoveField(
            model_name='customuser',
            name='picture',
        ),
        migrations.RemoveField(
            model_name='customuser',
            name='work_experience',
        ),
        migrations.RemoveField(
            model_name='jobapplymodel',
            name='experience',
        ),
        migrations.RemoveField(
            model_name='jobmodel',
            name='deadline',
        ),
        migrations.RemoveField(
            model_name='jobmodel',
            name='job_title',
        ),
        migrations.RemoveField(
            model_name='jobmodel',
            name='salary',
        ),
        migrations.CreateModel(
            name='recruiterprofile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('company_name', models.CharField(max_length=100, null=True)),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='seekerprofile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('skill', models.CharField(max_length=100, null=True)),
                ('resume', models.FileField(null=True, upload_to='resume')),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
